function getRandomImage() {
     let randomImage = new Array();
     randomImage[0] = "https://images.pexels.com/photos/858115/pexels-photo-858115.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500";
     randomImage[1] = "http://www.petsworld.in/blog/wp-content/uploads/2014/09/running-cute-puppies.jpg";
     randomImage[2] = "https://images.pexels.com/photos/142497/pexels-photo-142497.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500";
     randomImage[3] = "https://images.unsplash.com/photo-1543877087-ebf71fde2be1?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60";
     randomImage[4] = "https://wi.wallpapertip.com/wsimgs/156-1565522_puppies-desktop-wallpaper-desktop-background-puppies.jpg";
     randomImage[5] = "https://images.unsplash.com/photo-1501265976582-c1e1b0bbaf63?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60";

     var number = Math.floor(Math.random() * randomImage.length);

     //return the images generated by a random number
     document.querySelector(".image-large").innerHTML = '<img class="thumbnail" src="' + randomImage[number] + '" />';

     let randomHargaCorret = new Array();
     randomHargaCorret[0] = "Rp 100.12045";
     randomHargaCorret[1] = "Rp 999.12045";
     randomHargaCorret[2] = "Rp 888.12045";
     randomHargaCorret[3] = "Rp 777.12045";
     randomHargaCorret[4] = "Rp 666.12045";
     randomHargaCorret[5] = "Rp 555.12045";

     let randomHarga = new Array();
     randomHarga[0] = "Rp 90.12045";
     randomHarga[1] = "Rp 19.12045";
     randomHarga[2] = "Rp 18.12045";
     randomHarga[3] = "Rp 17.12045";
     randomHarga[4] = "Rp 16.12045";
     randomHarga[5] = "Rp 11.12045";

     let numberCorret = Math.floor(Math.random() * randomHargaCorret.length)

     document.querySelector(".price-detail-corret").innerHTML = '<p class="price-detail-corret">' + randomHargaCorret[numberCorret] + ' </p>';
     document.querySelector(".price-detail").innerHTML = '<p class="price-detail">' + randomHarga[numberCorret] + ' </p>';


}